CREATE DATABASE Meha_Outdoor_DB
GO
USE Meha_Outdoor_DB
GO
CREATE TABLE Kategoriler
(
ID INT IDENTITY (1,1),
Ad NVARCHAR(250)
CONSTRAINT pk_kategori_ID PRIMARY KEY(ID)
)
GO
CREATE TABLE Markalar
(
ID INT IDENTITY (10,1),
Ad NVARCHAR(250),
Mensei NVARCHAR(150),
CONSTRAINT pk_marka_ID PRIMARY KEY(ID)
)
GO
CREATE TABLE Tedarikciler
(
ID INT IDENTITY(1,1),
Firma NVARCHAR(250),
YetkiliKisi NVARCHAR(150),
Telefon NVARCHAR (11),
Alis_Fiyati DECIMAL(18,2),
CONSTRAINT pk_tedarikci_ID PRIMARY KEY(ID)
)
GO
CREATE TABLE Urunler
(
ID INT IDENTITY (100,1),
Ad NVARCHAR(200),
Kategori_ID INT,
Marka_ID INT,
Aciklama NVARCHAR(500),
Fiyat DECIMAL(18,2),
CONSTRAINT pk_urun_ID PRIMARY KEY(ID),
CONSTRAINT fk_kategori FOREIGN KEY(Kategori_ID) REFERENCES Kategoriler(ID),
CONSTRAINT fk_marka FOREIGN KEY(Marka_ID) REFERENCES Markalar(ID)
)
GO
CREATE TABLE Satislar
(
ID INT IDENTITY(1,1),
Urun_ID INT,
Adet SMALLINT,
Kar DECIMAL(18,2)
)