CREATE DATABASE Meha_Outdoor_DB
GO
USE Meha_Outdoor_DB
GO
CREATE TABLE Personeller
(
ID INT IDENTITY(1,1),
Ad NVARCHAR(50) NOT NULL,
Soyad NVARCHAR(50) NOT NULL,
Telefon NVARCHAR(11),
Maas DECIMAL(18,2) NOT NULL,
CONSTRAINT pk_personel_ID PRIMARY KEY(ID)
)
GO
CREATE TABLE Tedarikciler
(
ID INT IDENTITY(1,1),
Firma NVARCHAR(250) NOT NULL,
Yetkili NVARCHAR(150) NOT NULL,
Telefon NVARCHAR(11) NOT NULL,
AlisFiyat DECIMAL(18,2),
CONSTRAINT pk_tedarikci_ID PRIMARY KEY(ID)
)
GO
CREATE TABLE Markalar
(
ID INT IDENTITY(10,1),
Ad NVARCHAR(250) NOT NULL,
Mensei NVARCHAR(150),
CONSTRAINT pk_marka_ID PRIMARY KEY(ID)
)
GO
CREATE TABLE Kategoriler
(
ID INT IDENTITY(100,1),
Ad NVARCHAR(250),
AltKategori_ID INT,
CONSTRAINT pk_kategori_ID PRIMARY KEY(ID),
CONSTRAINT fk_altKategori_ID FOREIGN KEY(AltKategori_ID) REFERENCES Kategoriler(ID)
)
GO
CREATE TABLE Nakliyeciler
(
ID INT IDENTITY(1,1),
FirmaAdi NVARCHAR(250),
Yetkili NVARCHAR(150),
Telefon NVARCHAR(11)
CONSTRAINT pk_nakliye_ID PRIMARY KEY(ID)
)
GO
CREATE TABLE Urunler
(
ID INT IDENTITY(1000,1),
Ad NVARCHAR(250),
Kategori_ID INT,
Marka_ID INT,
Aciklama NVARCHAR(500),
Fiyat DECIMAL(18,2),
Stok INT,
GuvenlikStogu INT,
CONSTRAINT pk_urun_ID PRIMARY KEY(ID),
CONSTRAINT fk_kategoriID FOREIGN KEY(Kategori_ID) REFERENCES Kategoriler(ID),
CONSTRAINT fk_markaID FOREIGN KEY(Marka_ID) REFERENCES Markalar(ID)
)
GO
CREATE TABLE Satislar
(
ID INT IDENTITY(1,1),
Urun_ID INT,
Personel_ID INT,
Adet SMALLINT,
Kargo_ID INT,
CONSTRAINT pk_satis_ID PRIMARY KEY(ID),
CONSTRAINT fk_urunlerID FOREIGN KEY(Urun_ID) REFERENCES Urunler(ID),
CONSTRAINT fk_personellerID FOREIGN KEY(Personel_ID) REFERENCES Personeller(ID),
CONSTRAINT fk_kargolarID FOREIGN KEY(Kargo_ID) REFERENCES Nakliyeciler(ID)
)